name: Cross-Platform Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write # ✅ Required to create GitHub Releases

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: scripts

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          venv\Scripts\pip install --upgrade pip
          venv\Scripts\pip install -r requirements.txt
          venv\Scripts\pip uninstall -y enum34

      - name: Obfuscate with PyArmor
        run: |
          venv\Scripts\pyarmor gen --output dist-obf transcription.py
          copy dist-obf\transcription.py transcription.py

      - name: Build executable with PyInstaller
        run: |
          venv\Scripts\pyinstaller transcription_windows.spec

      - name: Copy built exe to Electron build folder
        run: |
          mkdir ..\build\transcription
          copy dist\transcription.exe ..\build\transcription\transcription.exe

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Build Electron app (Windows)
        run: npm run build:win

      - name: Upload Windows files to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PortAudio (for PyAudio)
        run: brew install portaudio

      - name: Install Python dependencies
        run: |
          cd scripts
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip uninstall -y enum34

      - name: Obfuscate with PyArmor
        run: |
          cd scripts
          source venv/bin/activate
          pyarmor gen --output dist-obf transcription.py
          cp dist-obf/transcription.py transcription.py

      - name: Build executable with PyInstaller
        run: |
          cd scripts
          source venv/bin/activate
          pyinstaller transcription_mac.spec

      - name: Copy built binary to Electron build folder
        run: |
          mkdir -p build/transcription
          cp scripts/dist/transcription build/transcription/transcription

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Build Electron app (macOS)
        run: npm run build:mac

      - name: Debug dist contents
        run: ls -al dist

      - name: Upload macOS files to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
