name: Cross-Platform Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: scripts

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      # 🔹 NON-ASR BUILD
      - name: Build Electron NON-ASR app (Windows)
        run: npm run build:win

      - name: Upload Windows NON-ASR files
        uses: softprops/action-gh-release@v1
        with:
          repository: InterviewSpeaker-Releases/releases
          files: |
            dist/InterviewSpeaker*.exe
            dist/InterviewSpeaker*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

      # 🔹 ASR BUILD (Python setup starts *after* non-ASR is done)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          venv\Scripts\pip install --upgrade pip
          venv\Scripts\pip install -r requirements.txt
          venv\Scripts\pip uninstall -y enum34

      - name: Build PyInstaller EXE
        run: venv\Scripts\pyinstaller transcription_windows.spec

      - name: Copy EXE to Electron build folder
        run: |
          mkdir ..\build\transcription
          copy dist\transcription.exe ..\build\transcription\transcription.exe

      - name: Build Electron ASR app (Windows)
        run: npm run build:win-asr

      - name: Upload Windows ASR files
        uses: softprops/action-gh-release@v1
        with:
          repository: InterviewSpeaker-Releases/releases
          files: |
            dist/InterviewSpeakerASR*.exe
            dist/InterviewSpeakerASR*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      # 🔹 NON-ASR BUILD
      - name: Build Electron NON-ASR app (macOS)
        run: npm run build:mac

      - name: Upload macOS NON-ASR files
        uses: softprops/action-gh-release@v1
        with:
          repository: InterviewSpeaker-Releases/releases
          files: |
            dist/InterviewSpeaker*.dmg
            dist/InterviewSpeaker*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

      # 🔹 ASR BUILD (Python setup starts *after* non-ASR is done)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PortAudio (for PyAudio)
        run: brew install portaudio

      - name: Install Python dependencies
        run: |
          cd scripts
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip uninstall -y enum34

      - name: Build PyInstaller binary (macOS)
        run: |
          cd scripts
          source venv/bin/activate
          pyinstaller transcription_mac.spec

      - name: Copy binary to Electron build folder
        run: |
          mkdir -p build/transcription
          cp scripts/dist/transcription build/transcription/transcription

      - name: Build Electron ASR app (macOS)
        run: npm run build:mac-asr

      - name: Upload macOS ASR files
        uses: softprops/action-gh-release@v1
        with:
          repository: InterviewSpeaker-Releases/releases
          files: |
            dist/InterviewSpeakerASR*.dmg
            dist/InterviewSpeakerASR*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
